export const COVID19ModalText ='&lt;p&gt;For your safety, and the safety of your community and healthcare providers we want to direct you to the best method of care.&lt;/p&gt;&lt;p&gt;Help us provide you with the right care in the right way by scheduling a video visit if any of the below apply to you.&lt;/p&gt;&lt;ul class=&quot;angle-bullets&quot;&gt;&lt;li&gt;In the last 14 days, I have tested positive for COVID-19 (coronavirus).&lt;/li&gt;&lt;li&gt;I am awaiting COVID-19 test results.&lt;/li&gt;&lt;li&gt;In the last 14 days, I have been in &lt;span id=&quot;contact&quot; class=&quot;tooltip-link&quot; &gt;close contact&lt;/span&gt; with someone who was confirmed or suspected to have COVID-19.&lt;/li&gt;&lt;li&gt;I have one or more &lt;span id=&quot;symptoms&quot; class=&quot;tooltip-link&quot;&gt;symptoms&lt;/span&gt; of COVID-19.&lt;/li&gt;&lt;/ul&gt;&lt;p class=&quot;footer&quot;&gt;Video visits can be scheduled via self-service in the Find Care section or by calling your clinic.&lt;/p&gt;&lt;hr/&gt;&lt;div class= &quot;row&quot;&gt; &lt;div class=&quot;offset-lg-2 col-lg-8 col-xs-12 acknowledgeFooter&quot;&gt;&lt;p class=&quot;footer1&quot;&gt;I have read the above and agree to schedule a video visit if any of those items apply to me.&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;';

export const COVID19ModalButtonText="CONTINUE";

export const COVID19ModalHeaderText="We’re in this together!";

export const COVID19ModalToolTips ="symptoms^&lt;p class='heading'&gt;COVID-19 SYMPTOMS&lt;/p&gt;&lt;div class='symptoms-main'&gt;&lt;div class='left'&gt;&lt;ul class='angle-bullets'&gt;&lt;li&gt;Chills&lt;/li&gt;&lt;li&gt;Sore throat&lt;/li&gt;&lt;li&gt;Cough&lt;/li&gt;&lt;li&gt;Loss of smell&lt;/li&gt;&lt;li&gt;Loss of taste&lt;/li&gt; &lt;li&gt;Vomiting&lt;/li&gt; &lt;/ul&gt;&lt;/div&gt;&lt;div class='right'&gt;&lt;ul class='angle-bullets'&gt;&lt;li&gt;Diarrhea&lt;/li&gt;&lt;li&gt;Severe headache&lt;/li&gt;&lt;li&gt;Fever&lt;/li&gt;&lt;li&gt;Muscle pain&lt;/li&gt;&lt;li&gt;Shortness of breath&lt;/li&gt; &lt;li&gt;Congestion or Runny nose&lt;/li&gt; &lt;/ul&gt;&lt;/div&gt;&lt;/div&gt;~contact^&lt;p class='heading'&gt;WHAT IS CLOSE CONTACT?&lt;/p&gt;&lt;p&gt;Close contact is being within approximately six feet of a person for over 15 minutes.&lt;/p&gt;";

export const buttonLabel = "View Modal";
